{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{foreach $attribute.content as $SelectedOptions}
{foreach $attribute.class_content.options as $Options}
{if eq( $Options.id, $SelectedOptions )}
{$Options.name|wash( xhtml )}<br/>
{/if}
{/foreach}
{/foreach}
