{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{foreach $attribute.class_content.options as $Options}
{if inarray( $Options.id, $attribute.content )}
{$Options.name|wash( xhtml )}<br/>
{/if}
{/foreach}
