<?php
/**
 * Autoloader definition for eZ Publish Extension files.
 *
 * @copyright Copyright (C) 1999-2011 eZ Systems AS. All rights reserved.
 * @license http://ez.no/licenses/gnu_gpl GNU General Public License v2.0
 * @version  4.2011
 * @package kernel
 *
 */

return array(
      'EnchantSpell'                        => 'extension/ezoe/modules/ezoe/classes/EnchantSpell.php',
      'GoogleSpell'                         => 'extension/ezoe/modules/ezoe/classes/GoogleSpell.php',
      'JSMin'                               => 'extension/ezjscore/lib/jsmin.php',
      'JSMinException'                      => 'extension/ezjscore/lib/jsmin.php',
      'Moxiecode_JSON'                      => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'Moxiecode_JSONReader'                => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'PSpell'                              => 'extension/ezoe/modules/ezoe/classes/PSpell.php',
      'PSpellShell'                         => 'extension/ezoe/modules/ezoe/classes/PSpellShell.php',
      'ReCaptchaResponse'                   => 'extension/ezcomments/classes/recaptchalib.php',
      'SpellChecker'                        => 'extension/ezoe/modules/ezoe/classes/SpellChecker.php',
      'eZContentClassEditDeferredHandler'   => 'extension/ezscriptmonitor/classes/ezcontentclasseditdeferredhandler.php',
      'eZFindElevateConfiguration'          => 'extension/ezfind/classes/ezfindelevateconfiguration.php',
      'eZFindInfo'                          => 'extension/ezfind/ezinfo.php',
      'eZFindResultNode'                    => 'extension/ezfind/classes/ezfindresultnode.php',
      'eZFindResultObject'                  => 'extension/ezfind/classes/ezfindresultobject.php',
      'eZFindServerCallFunctions'           => 'extension/ezfind/classes/ezfindservercallfunctions.php',
      'eZIEEzcConversions'                  => 'extension/ezie/classes/interfaces/conversions.php',
      'eZIEEzcGDHandler'                    => 'extension/ezie/classes/handlers/gd.php',
      'eZIEEzcImageMagickHandler'           => 'extension/ezie/classes/handlers/magick.php',
      'eZIEImageAction'                     => 'extension/ezie/classes/image_action.php',
      'eZIEImageAnalyzer'                   => 'extension/ezie/classes/image_analyzer.php',
      'eZIEImageFilterBW'                   => 'extension/ezie/classes/image_filter_bw.php',
      'eZIEImageFilterBrightness'           => 'extension/ezie/classes/image_filter_brightness.php',
      'eZIEImageFilterContrast'             => 'extension/ezie/classes/image_filter_contrast.php',
      'eZIEImageFilterSepia'                => 'extension/ezie/classes/image_filter_sepia.php',
      'eZIEImagePreAction'                  => 'extension/ezie/classes/image_pre_action.php',
      'eZIEImageToolCrop'                   => 'extension/ezie/classes/image_tool_crop.php',
      'eZIEImageToolFlipHorizontally'       => 'extension/ezie/classes/image_tool_flip_horizontally.php',
      'eZIEImageToolFlipVertically'         => 'extension/ezie/classes/image_tool_flip_vertically.php',
      'eZIEImageToolPixelate'               => 'extension/ezie/classes/image_tool_pixelate.php',
      'eZIEImageToolResize'                 => 'extension/ezie/classes/image_tool_resize.php',
      'eZIEImageToolRotation'               => 'extension/ezie/classes/image_tool_rotation.php',
      'eZIEImageToolWatermark'              => 'extension/ezie/classes/image_tool_watermark.php',
      'eZIEezcImageConverter'               => 'extension/ezie/classes/image_converter.php',
      'eZMultiuploadHandler'                => 'extension/ezmultiupload/classes/ezmultiuploadhandler.php',
      'eZMultiuploadHandlerInterface'       => 'extension/ezmultiupload/classes/ezmultiuploadhandlerinterface.php',
      'eZOEInputParser'                     => 'extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php',
      'eZOETemplateUtils'                   => 'extension/ezoe/autoloads/ezoetemplateutils.php',
      'eZOEXMLInput'                        => 'extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php',
      'eZOOConverter'                       => 'extension/ezodf/classes/ezooconverter.php',
      'eZOOGenerator'                       => 'extension/ezodf/classes/ezoogenerator.php',
      'eZOOImport'                          => 'extension/ezodf/classes/ezooimport.php',
      'eZOpenofficeUploadHandler'           => 'extension/ezodf/uploadhandlers/ezopenofficeuploadhandler.php',
      'eZRESTODFHandler'                    => 'extension/ezodf/classes/ezrestodfhandler.php',
      'eZScheduledScript'                   => 'extension/ezscriptmonitor/classes/ezscheduledscript.php',
      'eZScriptMonitorInfo'                 => 'extension/ezscriptmonitor/ezinfo.php',
      'eZSolr'                              => 'extension/ezfind/search/plugins/ezsolr/ezsolr.php',
      'eZSolrBase'                          => 'extension/ezfind/classes/ezsolrbase.php',
      'eZSolrDoc'                           => 'extension/ezfind/classes/ezsolrdoc.php',
      'ezauthorSolrStorage'                 => 'extension/ezfind/classes/solrstorage/ezauthorsolrstorage.php',
      'ezbinaryfileSolrStorage'             => 'extension/ezfind/classes/solrstorage/ezbinaryfilesolrstorage.php',
      'ezcomAddCommentTool'                 => 'extension/ezcomments/classes/ezcomaddcommenttool.php',
      'ezcomComment'                        => 'extension/ezcomments/classes/ezcomcomment.php',
      'ezcomCommentCommonManager'           => 'extension/ezcomments/classes/ezcomcommentcommonmanager.php',
      'ezcomCommentManager'                 => 'extension/ezcomments/classes/ezcomcommentmanager.php',
      'ezcomCommentsType'                   => 'extension/ezcomments/datatypes/ezcomcomments/ezcomcommentstype.php',
      'ezcomCookieManager'                  => 'extension/ezcomments/classes/ezcomcookiemanager.php',
      'ezcomEditCommentTool'                => 'extension/ezcomments/classes/ezcomeditcommenttool.php',
      'ezcomFormTool'                       => 'extension/ezcomments/classes/ezcomformtool.php',
      'ezcomFunctionCollection'             => 'extension/ezcomments/classes/ezcomfunctioncollection.php',
      'ezcomNotification'                   => 'extension/ezcomments/classes/ezcomnotification.php',
      'ezcomNotificationEmailManager'       => 'extension/ezcomments/classes/ezcomnotificationemailmanager.php',
      'ezcomNotificationManager'            => 'extension/ezcomments/classes/ezcomnotifcationmanager.php',
      'ezcomPermission'                     => 'extension/ezcomments/classes/ezcompermission.php',
      'ezcomPostHelper'                     => 'extension/ezcomments/classes/ezcomposthelper.php',
      'ezcomServerFunctions'                => 'extension/ezcomments/classes/ezcomserverfunctions.php',
      'ezcomSubscriber'                     => 'extension/ezcomments/classes/ezcomsubscriber.php',
      'ezcomSubscription'                   => 'extension/ezcomments/classes/ezcomsubscription.php',
      'ezcomSubscriptionManager'            => 'extension/ezcomments/classes/ezcomsubscriptionmanager.php',
      'ezcomUtility'                        => 'extension/ezcomments/classes/ezcomutility.php',
      'ezcommentsInfo'                      => 'extension/ezcomments/ezinfo.php',
      'ezdatatypeSolrStorage'               => 'extension/ezfind/classes/ezdatatypesolrstorage.php',
      'ezdateSolrStorage'                   => 'extension/ezfind/classes/solrstorage/ezdatesolrstorage.php',
      'ezdatetimeSolrStorage'               => 'extension/ezfind/classes/solrstorage/ezdatetimesolrstorage.php',
      'ezenumSolrStorage'                   => 'extension/ezfind/classes/solrstorage/ezenumsolrstorage.php',
      'ezfBaseException'                    => 'extension/ezfind/classes/exceptions/ezfexception.php',
      'ezfModuleFunctionCollection'         => 'extension/ezfind/classes/ezfmodulefunctioncollection.php',
      'ezfSearchResultInfo'                 => 'extension/ezfind/classes/ezfsearchresultinfo.php',
      'ezfSolrDocumentFieldBase'            => 'extension/ezfind/classes/ezfsolrdocumentfieldbase.php',
      'ezfSolrDocumentFieldDummyExample'    => 'extension/ezfind/classes/ezfsolrdocumentfielddummyexample.php',
      'ezfSolrDocumentFieldGmapLocation'    => 'extension/ezfind/classes/ezfsolrdocumentfieldgmaplocation.php',
      'ezfSolrDocumentFieldName'            => 'extension/ezfind/classes/ezfsolrdocumentfieldname.php',
      'ezfSolrDocumentFieldObjectRelation'  => 'extension/ezfind/classes/ezfsolrdocumentfieldobjectrelation.php',
      'ezfSolrDocumentFieldXML'             => 'extension/ezfind/classes/ezfsolrdocumentfieldxml.php',
      'ezfSolrException'                    => 'extension/ezfind/classes/exceptions/ezfsolrexception.php',
      'ezfSolrStorage'                      => 'extension/ezfind/classes/ezfsolrstorage.php',
      'ezfSolrUtils'                        => 'extension/ezfind/classes/ezfsolrutils.php',
      'ezfUpdateSearchIndexSolr'            => 'extension/ezfind/bin/php/updatesearchindexsolr.php',
      'ezfeZPSolrQueryBuilder'              => 'extension/ezfind/classes/ezfezpsolrquerybuilder.php',
      'ezjscAccessTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscaccesstemplatefunctions.php',
      'ezjscAjaxContent'                    => 'extension/ezjscore/classes/ezjscajaxcontent.php',
      'ezjscEncodingTemplateFunctions'      => 'extension/ezjscore/autoloads/ezjscencodingtemplatefunctions.php',
      'ezjscPacker'                         => 'extension/ezjscore/classes/ezjscpacker.php',
      'ezjscPackerTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscpackertemplatefunctions.php',
      'ezjscServerFunctions'                => 'extension/ezjscore/classes/ezjscserverfunctions.php',
      'ezjscServerFunctionsJs'              => 'extension/ezjscore/classes/ezjscserverfunctionsjs.php',
      'ezjscServerFunctionsNode'            => 'extension/ezjscore/classes/ezjscserverfunctionsnode.php',
      'ezjscServerFunctionsPublishingQueue' => 'extension/ezjscore/classes/ezjscserverfunctionspublishingqueue.php',
      'ezjscServerRouter'                   => 'extension/ezjscore/classes/ezjscserverrouter.php',
      'ezjscoreInfo'                        => 'extension/ezjscore/ezinfo.php',
      'ezkeywordSolrStorage'                => 'extension/ezfind/classes/solrstorage/ezkeywordsolrstorage.php',
      'ezmatrixSolrStorage'                 => 'extension/ezfind/classes/solrstorage/ezmatrixsolrstorage.php',
      'ezmultioptionSolrStorage'            => 'extension/ezfind/classes/solrstorage/ezmultioptionsolrstorage.php',
      'ezmultiuploadInfo'                   => 'extension/ezmultiupload/ezinfo.php',
      'ezobjectrelationlistSolrStorage'     => 'extension/ezfind/classes/solrstorage/ezobjectrelationlistsolrstorage.php',
      'ezodfInfo'                           => 'extension/ezodf/ezinfo.php',
      'ezoeInfo'                            => 'extension/ezoe/ezinfo.php',
      'ezoeServerFunctions'                 => 'extension/ezoe/classes/ezoeserverfunctions.php',
      'ezoptionSolrStorage'                 => 'extension/ezfind/classes/solrstorage/ezoptionsolrstorage.php',
      'ezpFileArchive'                      => 'extension/ezfind/classes/archive/filestorage/ezpfilearchive.php',
      'ezpFileArchiveFactory'               => 'extension/ezfind/classes/archive/filestorage/ezpfilearchivefactory.php',
      'ezpFileArchiveFileSystem'            => 'extension/ezfind/classes/archive/filestorage/ezpfilearchivefilesystem.php',
      'ezpRestApiProvider'                  => 'extension/ezprestapiprovider/classes/rest_provider.php',
      'ezpRestApiViewController'            => 'extension/ezprestapiprovider/classes/view_controller.php',
      'ezpRestContentController'            => 'extension/ezprestapiprovider/classes/controllers/content.php',
      'ezpRestContentModel'                 => 'extension/ezprestapiprovider/classes/models/rest_content_model.php',
      'ezpriceSolrStorage'                  => 'extension/ezfind/classes/solrstorage/ezpricesolrstorage.php',
      'ezproductcategorySolrStorage'        => 'extension/ezfind/classes/solrstorage/ezproductcategorysolrstorage.php',
      'ezrangeoptionSolrStorage'            => 'extension/ezfind/classes/solrstorage/ezrangeoptionsolrstorage.php',
      'ezselectionSolrStorage'              => 'extension/ezfind/classes/solrstorage/ezselectionsolrstorage.php',
      'ezurlSolrStorage'                    => 'extension/ezfind/classes/solrstorage/ezurlsolrstorage.php',
      'ezuserSolrStorage'                   => 'extension/ezfind/classes/solrstorage/ezusersolrstorage.php',
      'ezxmltextSolrStorage'                => 'extension/ezfind/classes/solrstorage/ezxmltextsolrstorage.php',
    );

?>
