<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ez_aya_sit",
                     "development" => false,
                     "summary" => "ez_aya_sit extension",
                     "description" => "This package contains the ez_aya_sit eZ Publish extension",
                     "vendor" => false,
                     "vendor-dir" => "local",
                     "priority" => false,
                     "type" => "extension",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.4.0",
                                           "named-version" => "4.4" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "jmace@ayaline.com",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1308132984",
                                           "host" => "demo.ez44.lnet.fr",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1308132984",
                                                  "person" => "Administrator User",
                                                  "email" => "jmace@ayaline.com",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezextension",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "extension-ez_aya_sit",
                                                "sub-directory" => "ezextension" ) ),
                     "uninstall" => array( array( "type" => "ezextension",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "extension-ez_aya_sit",
                                                  "sub-directory" => "ezextension" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/local";
?>
